allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    es5-ext: true
    unrs-resolver: true
onlyBuiltDependencies:
    - '@swc/core'
overrides:
    '@babel/core': '>=7.29.6'
    '@jest/core': ^30.4.2
    '@jest/environment': ^30.4.1
    '@jest/globals': ^30.4.1
    '@jest/transform': ^30.4.1
    '@jest/types': ^30.4.1
    braces: '>=3.0.3'
    brace-expansion: '>=5.0.7'
    browserslist: '>=4.28.7'
    decode-uri-component: '>=0.5.0'
    fast-uri: '>=3.1.5'
    glob-parent: ^5.1.2
    jest-cli: ^30.4.2
    jest-config: ^30.4.2
    jest: ^30.4.2
    js-yaml: '>=4.3.1'
    lodash: '>=4.18.0'
    marked': ^4.0.10
    minimatch: '>=10.2.3'
    nanoid: '>=3.3.16'
    postcss: '>=8.5.23'
    serialize-javascript: '>=7.0.5'
    test-exclude>minimatch: ^3.1.2
    webpack: '>=5.104.1'
    jest-runtime: ^30.4.2
